config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about',      to: 'static_pages#about'
  get 'help',       to: 'static_pages#help'
  get 'contact',    to: 'static_pages#contact'

  devise_for :users

  resources :users, only:[:show, :index]
  resources :posts, except:[:new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  ALLOWED_CONTENT_TYPES = %q(
    image/jpeg
    image/png
    image/gif
    image/bmp
).freeze
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(date: :desc) }
  validates :user_id, :training, :date, :weight, presence: true
  validates :user_id, uniqueness: { scope: [:date] }
  validates :training, :content, length: { maximum: 250 }
  mount_uploader :image, ImageUploader
  validate :image_size
  #->validateメソッドは引数にシンボルを取り、そのシンボル名に対応したメソッドを呼び出す
  #   =自分オリジナルのvalidationを使える

  private

    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  validates :name, :started_at, :aim, :weight, :height, presence: true

  def init_bmi
    (weight / (height ** 2)).round(2)
  end

  def latest_bmi
    (latest_weight / (height ** 2)).round(2)
  end

  def latest_weight
    posts.ids.empty? ? weight : posts.first.weight
  end

  def by_target_weight
    (latest_weight - aim).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  if Rails.env.production? || ENV["RESCUE_EXCEPTIONS"]
    rescue_from StandardError, with: :rescue_internal_server_error
    rescue_from ActiveRecord::RecordNotFound, with: :rescue_not_found
    rescue_from ActionController::ParameterMissing, with: :rescue_bad_request
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :started_at, :finished_at, :aim, :weight, :bmi, :height])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :started_at, :finished_at, :aim, :weight, :bmi, :height])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :started_at, :finished_at, :aim, :weight, :bmi, :height])
    end

  private

    def rescue_internal_server_error(exception)
      render "/errors/internal_server_error", status: 500, layout: "application", formats: [:html]
    end

    def rescue_not_found(exception)
      render "/errors/not_found", status: 404, layout: "application", formats: [:html]
    end

    def rescue_bad_request(exception)
      render "/errors/bad_request", status: 400, layout: "application", formats: [:html]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :correct_user, only: [:destroy, :edit]

  def index
    @posts = Post.all.page(params[:page]).per(24)
  end

  def show
    @post  = Post.find(params[:id])
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted!"
    redirect_to root_url
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_parameter)
      flash[:success] = "Post Updated!"
      redirect_to post_url
    else
      flash[:danger] = "Post Update is invalid!"
      render 'edit'
    end
  end

  def create
    @post = current_user.posts.build(post_parameter)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      flash[:danger] = "Post Not created!"
      redirect_to root_url
    end
  end


  private

  def post_parameter
    params.require(:post).permit(:content, :weight, :height, :date, :aim, :training, :image, :morning, :lunch, :dinner)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @posts = current_user.posts.all
      @post  = current_user.posts.build
    end
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user           = User.find(params[:id])
    @posts          = @user.posts.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "100Days Of Training"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
      <small class="d-block mb-3 text-muted">&copy; 2018-2019</small>
    </div>
    <div class="col-6 col-md">
      <%=link_to "HOME", root_path %>
    </div>
    <div class="col-6 col-md">
      <%=link_to "ABOUT", about_path %>
    </div>
    <div class="col-6 col-md">
      <%=link_to "HELP", help_path %>
    </div>
    <div class="col-6 col-md">
      <%=link_to "CONTACT", contact_path %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "100Days Of Training", root_path, id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "HOME", root_path, class: "nav-link" %><span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to "ABOUT", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "HELP", help_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "CONTACT", contact_path, class: "nav-link" %>
      </li>
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            SETTING
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "All USERS", users_path, class: "dropdown-item" %>
            <%= link_to "All POSTS", posts_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "EDIT USER", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, data: { confirm: "You sure?" }, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-92629648-9"></script>
  <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
          dataLayer.push(arguments);
      }

      gtag('js', new Date());

      gtag('config', 'UA-92629648-9');
  </script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="<%= "landding-page" unless user_signed_in? %>">
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_post.html.erb
<div class="card-feed">
  <% @posts.each do |post| %>
    <div class="card">
      <%= image_tag post.image? ? post.image.url(:thumb) : ("crossfit-thumb.jpg") %>
      <div class="card-body">
        <h4 class="card-title"><%= (post.date - @user.started_at + 1).to_i %>日目</h4>
        <span class="card-text">
        <table style="border-collapse: collapse; width: 100%;">
          <tbody>
          <tr>
            <td style="width: 20%;">日　　時:</td>
            <td style="width: 20%;"><%= post.date %></td>
          </tr>
          <tr>
            <td style="width: 20%;">体　　重:</td>
            <td style="width: 20%;"><%= post.weight %>kg</td>
          </tr>
          <tr>
            <td style="width: 20%;">B　M　I:</td>
            <td style="width: 20%;"><%= (post.weight / (@user.height ** 2)).round(2) %>%</td>
          </tr>
          </tbody>
        </table>
          <%= link_to "詳細をみる", post %><br/>
        <div class="timestamp"><%= time_ago_in_words(post.created_at) %> ago.</div>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<div class="container">
  <h1>Edit Post</h1>
  <div class="card-show">
    <%= image_tag @post.image? ? @post.image.url(:medium) : ("crossfit-534615.jpg"), width: "100%" %>
    <div class="post-form">
      <%= form_for(@post) do |f| %>
        <div class="form-row">
          <div class="form-group col-md-4 base_info">
            <%= f.label :本日の体重 %><br/>
            <%= f.number_field :weight, step: 0.01, value: @post.weight, class: "weight-field" %>kg
          </div>
          <div class="form-group col-md-4 base_info">
            <%= f.label :Photo %>
            <%= f.file_field :image %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :トレーニング内容 %>
          <%= f.text_area :training, placeholder: "トレーニング内容", class: "content-field" %>
        </div>
        <div class="form-group">
          <%= f.label :【朝食】 %><br/>
          <%= f.text_area :morning, placeholder: "朝食は何を食べましたか？", class: "content-field" %>
        </div>
        <div class="form-group">
          <%= f.label :【昼食】 %><br/>
          <%= f.text_area :lunch, placeholder: "昼食は何を食べましたか？", class: "content-field" %>
        </div>
        <div class="form-group">
          <%= f.label :【夕食】 %><br/>
          <%= f.text_area :dinner, placeholder: "夕食は何を食べましたか？", class: "content-field" %>
        </div>
        <div class="form-group">
          <%= f.label :メモ %><br/>
          <%= f.text_area :content, placeholder: "Compose new Post", class: "content-field" %>
        </div>
        <div class="form-group">
          <%= f.date_select :date %>
        </div>
        <%= f.submit "Post", class: "btn btn-success" %>
      <% end %>
      <%= link_to "return Post page", post_path %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "All Posts") %>
<h2>ALL POSTS</h2>
<div class="card-feed">
  <% @posts.each do |post| %>
    <div class="card">
      <%= image_tag post.image? ? post.image.url(:thumb) : ("crossfit-thumb.jpg") %>
      <div class="card-body">
        <h4 class="card-title"><%= (post.date - post.user.started_at + 1).to_i %>日目</h4>
        <p class="card-text">
        <table style="border-collapse: collapse; width: 100%;">
          <tbody>
          <tr>
            <td style="width: 20%;"> User:</td>
            <td style="width: 20%;"><%= link_to post.user.name, post.user %></td>
          </tr>
          <tr>
            <td style="width: 20%;"> 日数:</td>
            <td style="width: 20%;"><%= (post.date - post.user.started_at + 1).to_i %>日目</td>
          </tr>
          <tr>
            <td style="width: 20%;">日時:</td>
            <td style="width: 20%;"><%= post.date %></td>
          </tr>
          <tr>
            <td style="width: 20%;">体重:</td>
            <td style="width: 20%;"><%= post.weight %>kg</td>
          </tr>
          <tr>
            <td style="width: 20%;">BMI:</td>
            <td style="width: 20%;"><%= (post.weight / current_user.height / current_user.height).round(2) %>%</td>
          </tr>
          </tbody>
        </table>
        <%= link_to "詳細をみる", post %>
        <div class="timestamp"><%= time_ago_in_words(post.created_at) %> ago.</div>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @posts, class: "pagination" %>

app/views/posts/show.html.erb
<% provide(:title, @post.user.name) %>
<div class="card-show">
  <%= image_tag @post.image? ? @post.image.url(:medium) : ("crossfit-medium.jpg"), class: "post-img" %>
  <h4 class="card-title">開始から<%= (@post.date - @post.user.started_at + 1).to_i %>日目</h4>
  <table class="card-text" style="border-collapse: collapse;">
    <tbody>
    <tr>
      <td class="content-in-card"><strong>日　　時</strong></td>
      <td class="card-in-table"><%= @post.date %></td>
    </tr>
    <tr>
      <td class="content-in-card"><strong>体　　重</strong></td>
      <td class="card-in-table"><%= @post.weight %>kg</td>
    </tr>
    <tr>
      <td class="content-in-card"><strong>B　M　I</strong></td>
      <td class="card-in-table"><%= (@post.weight / (@post.user.height**2)).round(2) %>%</td>
    </tr>
    <tr>
      <td class="content-in-card" ;><strong>トレーニング内容</strong></td>
      <td class="card-in-table"><%= simple_format(@post.training) %></td>
    </tr>
    <tr>
      <td class="content-in-card" ;><strong>朝食</strong></td>
      <td class="card-in-table" ;><%= simple_format(@post.morning) %></td>
    </tr>
    <tr>
      <td class="content-in-card" ;><strong>昼食</strong></td>
      <td class="card-in-table" ;><%= simple_format(@post.lunch) %></td>
    </tr>
    <tr>
      <td class="content-in-card" ;><strong>夕食</strong></td>
      <td class="card-in-table" ;><%= simple_format(@post.dinner) %></td>
    </tr>
    <tr>
      <td class="content-in-card" style="text-align: center;" colspan="2"><strong>メモ</strong></td>
    </tr>
    <tr>
      <td class="card-in-table" style="text-align: center; height: 100px;" colspan="2"><%= simple_format(@post.content) %></td>
    </tr>
    </tbody>
  </table>
  <div class="timestamp"><%= time_ago_in_words(@post.created_at) %> ago.</div>
  <% if current_user?(@post.user) %>
    <%= link_to "Edit", edit_post_path, class: "btn btn-info" %>
    <%= link_to "Delete", post_path, method: :delete, class: "btn btn-danger" %>
  <% end %>
  <%= link_to "Return Home", root_path, class: "btn btn-success" %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div class="flash">
  <% if flash[:danger] || flash[:success] %>
    <p><%= flash[:danger] || flash[:success] %></p>
  <% end %>
</div>

app/views/shared/_post_form.html.erb
<div class="post-form">
  <h2><%= (Date.today - current_user.started_at + 1).to_i %>/100日目</h2>
  <%= form_for @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-row">
      <div class="form-group col-md-2 base_info">
        <%= f.label :【本日の体重】 %><br/>
        <%= f.number_field :weight, step: 0.01, value: @posts.any? ? @posts.first.weight : current_user.weight, class: "weight-field" %>kg
      </div>
      <div class="form-group col-md-2 base_info">
        <%= f.label :【Photo】 %>
        <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png' %>
        <!-- ->acceptパラメータでPost.rbで定めたvalidationを反映するため-->
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        <%= f.label :【朝食】 %><br/>
        <%= f.text_area :morning, placeholder: "朝食は何を食べましたか？", class: "content-field" %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :【昼食】 %><br/>
        <%= f.text_area :lunch, placeholder: "昼食は何を食べましたか？", class: "content-field" %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :【夕食】 %><br/>
        <%= f.text_area :dinner, placeholder: "夕食は何を食べましたか？", class: "content-field" %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <%= f.label :【トレーニング内容】 %><br/>
        <%= f.text_area :training, placeholder: "トレーニング内容", class: "content-field" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :【メモ】 %><br/>
      <%= f.text_area :content, placeholder: "Compose new Post", class: "content-field" %>
    </div>
    <div class="form-group">
      <%= f.date_select :date %>
    </div>
    <%= f.submit "Post", class: "btn btn-success" %>
  <% end %>
</div>

<script type="text/javascript">
    $('#post_image').bind('change', function () {
        var size_in_megabytes = this.files[0].size / 1024 / 1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/shared/_user_top.html.erb
<% @user ||= current_user %>
<div class="position-relative overflow-hidden m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h5><%= @user.name %></h5>
    <h6>目標:<%= @user.aim %>kg</h6>
    <h6>達成まで:<%= @user.by_target_weight %>kg</h6>
    <p class="lead font-weight-normal">
    <div class="start-info">
      <table>
        <tbody style="border: 1px solid #000000">
        <tr>
          <td style="width: 200px"></td>
          <td style="width: 400px">開始時</td>
          <td style="width: 400px">現　在</td>
        </tr>
        <tr>
          <td style="width: 200px">日時</td>
          <td style="width: 400px"><%= @user.started_at %></td>
          <td style="width: 400px"><%= (Date.today - @user.started_at + 1).to_i %>/100日目</td>
        </tr>
        <tr>
          <td style="width: 200px">体重</td>
          <td style="width: 400px"><%= @user.weight %>kg</td>
          <td style="width: 400px"><%= @user.latest_weight %>kg</td>
        </tr>
        <tr>
          <td style="width: 200px">B M I</td>
          <td style="width: 400px"><%= @user.init_bmi %>%</td>
          <td style="width: 400px"><%= @user.latest_bmi  %>%</td>
        </tr>
        </tbody>
      </table>
    </div>
    </p>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>
<div class="btn-position">
  <%= link_to "Edit Account", edit_user_registration_path, class: "btn btn-primary" %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
  <%= link_to "Delete Account", user_registration_path, class: "btn btn-danger", method: :delete, data: { confirm: "You sure?" } %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="container">
  <div class="about-page">
    <h2>About 100Days Of Training</h2>
    <p>当サービスはダイエットや運動不足解消など様々な理由からトレーニングを始める人を支援するサービスです。</p>

    <p>このサービスでは、100日間のトレーニング継続を目標に、体重の記録やトレーニング内容の記録・共有ができます。</p>

    <p>SNSなどでの共有機能はつけず、コメントやいいね！などの機能も持たせていません。</p>

    <p>あくまでも黙々と続けていくためのサービスで、同じく黙々とトレーニングを継続している人達の頑張りを見ながら、あなた自身もトレーニングを継続させていきましょう。</p>


    <p style="color: red">*当サービスは<a href="https://twitter.com/all_akumasan">@all_akumasan</a>がプログラミング習得のために作成したサービスです。
    </p>
    <p style="color: red">開発状況によって予告なく閉鎖等を行う場合もあることを承知の上、ご利用をお願い致します。</p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container">
  <div class="about-page">
    <h2>問い合わせについて</h2>
    <p>当サービスは<a href="https://twitter.com/all_akumasan">@all_akumasan</a>によって運営されています。

      ご用のある方はこちらのDMまでご連絡ください。
    </p>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="container">
  <div class="about-page">
    <h2>当サービスの使い方</h2>
    <ul>
      <li>投稿は1日あたり1投稿のみ限定です。</li>
      <li>【本日の体重】を記入します。(必須)</li>
      <li>気になる部位の変化も記録したい場合には【Photo】に写真をアップロードします。写真はなくても投稿できます。</li>
      <li>【トレーニング内容】欄にその日に行ったトレーニング内容などを記入します。(必須)</li>
      <li>食事の状況なども記録しておきたい場合には【メモ】欄に記入します。</li>
      <li>トレーニングを行なった日を選択し、投稿します。</li>
    </ul>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <%= render 'shared/user_top' %>
  <%= render 'shared/post_form' %>
  <%= render @post %>
<% else %>
  <div class="top-page">
    <h1>Welcome to "100Days of Training"!</h1>
    <p>今日からあなたの100日間のトレーニングが始まります。</p>
    <p>ダイエットでも、マラソンでも、目的はなんでもOK。</p>
    <P>ここにはあなたと同じように、"100日間トレーニングを続ける"という共通した仲間がたくさん集まっています。</p>
    <p>仲間のトレーニング報告をみて、あなたもトレーニング報告をして、辛い時間も、達成感も、多くの仲間と共有していきましょう。</p>
    <div class="sign-up">
      <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-lg btn-primary" %><br/>
      <%= link_to "Log In", new_user_session_path %><br/>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h2>ALL USERS</h2>
<% @users.each do |user| %>
  <div class="card-users">
    <div class="card-body">
      <table style="border-collapse: collapse; width: 100%;">
        <tbody>
        <tr>
          <td style="width: 20%;"> User:</td>
          <td style="width: 20%;"><%= link_to user.name, user %></td>
        </tr>
        <tr>
          <td style="width: 20%;">残日数:</td>
          <td style="width: 20%;"><%= (100 - (user.posts.ids.count)) %>日</td>
        </tr>
        <tr>
          <td style="width: 20%;">目標まで:</td>
          <td style="width: 20%;"><%= ((user.posts.any? ? user.posts.first.weight : user.weight).to_f - (user.aim).to_f).round(2) %>kg</td>
        </tr>
        </tbody>
      </table>
      <%= link_to "詳細をみる", user %>
      <div class="timestamp"><%= time_ago_in_words(user.created_at) %> ago.</div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h5><%= current_user.name %></h5>
    <h6>目標:<%= current_user.aim %>kg</h6>
    <h6>達成まで:<%= @user.by_target_weight %>kg</h6>
    <p class="lead font-weight-normal">
    <div class="start-info">
      <table>
        <tbody style="border: 1px solid #000000">
        <tr>
          <td style="width: 200px"></td>
          <td style="width: 400px">開始時</td>
          <td style="width: 400px">現　在</td>
        </tr>
        <tr>
          <td style="width: 200px">日時</td>
          <td style="width: 400px"><%= @user.started_at %></td>
          <td style="width: 400px"><%= (Date.today - @user.started_at + 1).to_i %>/100日目</td>
        </tr>
        <tr>
          <td style="width: 200px">体重</td>
          <td style="width: 400px"><%= @user.weight %>kg</td>
          <td style="width: 400px"><%= @user.latest_weight %>kg</td>
        </tr>
        <tr>
          <td style="width: 200px">B M I</td>
          <td style="width: 400px"><%= @user.bmi %>%</td>
          <td style="width: 400px"><%= @user.latest_bmi %>%</td>
        </tr>
        </tbody>
      </table>
    </div>
    </p>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>

<%= render 'posts/post' %>